version: '3'

services:
  app:
    build:
      context: ./node
      dockerfile: Dockerfile.prod
    container_name: app
    entrypoint: dockerize -wait tcp://nginx:80 -timeout 60s -wait tcp://mysql:3306 -timeout 60s docker-entrypoint.sh npm run dev
    networks:
      - nodelan
    volumes:
      - ./node:/usr/src/app
    tty: true
    depends_on:
      - mysql
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile.prod
    container_name: nginx
    networks:
      - nodelan
    ports:
      - "80:80"
      - "8080:8080"
    links:
      - app
  mysql:    
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: mysql
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=peoples
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=mysql_user
    networks:
      - nodelan
networks:
  nodelan:
    driver: bridge