version: '3'

services:
  app:
    build:
      context: ./node
      dockerfile: Dockerfile.prod
    container_name: app
    entrypoint: dockerize -wait tcp://nginx:80 docker-entrypoint.sh npm run dev
    networks:
      - nodelan
    volumes:
      - ./node:/usr/src/app
    tty: true
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile.prod
    container_name: nginx
    networks:
      - nodelan
    ports:
      - "80:80"
    links:
      - app
networks:
  nodelan:
    driver: bridge